spring:
  application:
    name: service-zookeeper-client
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true
        register: false

server:
  port: 8063

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:8081/eureka/


logging:
  level:
    root: ERROR
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG
      mybatis: DEBUG
#  path: D:/temp/logs/zookeeper-client.log
  file: ./logs/zookeeper-client.log