spring:
  application:
    name: service-archaius


server:
  port: 8069

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/


logging:
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR
      hibernate: ERROR
      mybatis: ERROR
#  path: D:/temp/logs/archaius.log
  file: ./logs/archaius.log