spring:
  application:
    name: service-zookeeper-server
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true
        register: true
server:
  port: 8064

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:8081/eureka/


logging:
  level:
    root: ERROR
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG
      mybatis: DEBUG
#  path: D:/temp/logs/zookeeper-server.log
  file: ./logs/zookeeper-server.log