spring:
  application:
    name: service-feign

server:
  port: 8764

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/


logging:
  level:
    root: INFO
    org:
      springframework:
        web: ERROR
      hibernate: ERROR
      mybatis: ERROR
  path: D:/logs/
  file: ./logs/feign.log