spring:
  application:
    name: service-ribbon

server:
  port: 8077

eureka:
  instance:
      prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/


logging:
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR
      hibernate: ERROR
      mybatis: ERROR
#  path: D:/temp/logs/ribbon.log
  file: ./logs/ribbon.log